/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        surface: '#0b1326',
        'surface-dim': '#0b1326',
        'surface-bright': '#31394d',
        'surface-container-lowest': '#060e20',
        'surface-container-low': '#131b2e',
        'surface-container': '#171f33',
        'surface-container-high': '#222a3d',
        'surface-container-highest': '#2d3449',
        'on-surface': '#dae2fd',
        'on-surface-variant': '#d0c5af',
        'inverse-surface': '#dae2fd',
        'inverse-on-surface': '#283044',
        outline: '#99907c',
        'outline-variant': '#4d4635',
        'surface-tint': '#e9c349',
        primary: '#f2ca50',
        'on-primary': '#3c2f00',
        'primary-container': '#d4af37',
        'on-primary-container': '#554300',
        'inverse-primary': '#735c00',
        secondary: '#88d982',
        'on-secondary': '#003909',
        'secondary-container': '#005b14',
        'on-secondary-container': '#81d27c',
        tertiary: '#ffbfb8',
        'on-tertiary': '#690007',
        'tertiary-container': '#ff968c',
        'on-tertiary-container': '#90000e',
        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        'primary-fixed': '#ffe088',
        'primary-fixed-dim': '#e9c349',
        'on-primary-fixed': '#241a00',
        'on-primary-fixed-variant': '#574500',
        'secondary-fixed': '#a3f69c',
        'secondary-fixed-dim': '#88d982',
        'on-secondary-fixed': '#002204',
        'on-secondary-fixed-variant': '#005312',
        'tertiary-fixed': '#ffdad6',
        'tertiary-fixed-dim': '#ffb4ac',
        'on-tertiary-fixed': '#410003',
        'on-tertiary-fixed-variant': '#93000e',
        background: '#0b1326',
        'on-background': '#dae2fd',
        'surface-variant': '#2d3449',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        display: ['Montserrat', 'Inter', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'headline-xl': ['40px', {
          lineHeight: '48px',
          fontWeight: '700',
          letterSpacing: '0',
        }],
        'headline-xl-mobile': ['32px', {
          lineHeight: '40px',
          fontWeight: '700',
          letterSpacing: '0',
        }],
        'headline-lg': ['32px', {
          lineHeight: '40px',
          fontWeight: '600',
          letterSpacing: '0',
        }],
        'headline-md': ['24px', {
          lineHeight: '32px',
          fontWeight: '600',
        }],
        'body-lg': ['18px', {
          lineHeight: '28px',
          fontWeight: '400',
        }],
        'body-md': ['16px', {
          lineHeight: '24px',
          fontWeight: '400',
        }],
        'body-sm': ['14px', {
          lineHeight: '20px',
          fontWeight: '400',
        }],
        'label-md': ['12px', {
          lineHeight: '16px',
          fontWeight: '600',
          letterSpacing: '0.05em',
        }],
        'label-sm': ['10px', {
          lineHeight: '12px',
          fontWeight: '700',
          letterSpacing: '0.08em',
        }],
        'data-mono': ['14px', {
          lineHeight: '20px',
          fontWeight: '500',
        }],
      },
      borderRadius: {
        sm: '0.125rem',
        md: '0.375rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'stack-sm': '4px',
        'stack-md': '12px',
        'stack-lg': '24px',
        'section-gap': '64px',
      },
      maxWidth: {
        'container': '1280px',
      },
    },
  },
  plugins: [],
}
