/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        canvas: '#f3f5f9',
        ink: '#0f1b2d',
        line: '#e6e9ef',
        'line-strong': '#d7dbe4',
        panel: '#0d1526',
        'panel-2': '#131d33',
        surface: '#f3f5f9',
        'surface-dim': '#e9edf3',
        'surface-bright': '#ffffff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#ffffff',
        'surface-container': '#f8fafc',
        'surface-container-high': '#eef1f5',
        'surface-container-highest': '#e4e8ef',
        'on-surface': '#0f1b2d',
        'on-surface-variant': '#64748b',
        'inverse-surface': '#0f1b2d',
        'inverse-on-surface': '#f8fafc',
        outline: '#94a3b8',
        'outline-variant': '#d7dbe4',
        'surface-tint': '#0ea871',
        primary: '#0ea871',
        'on-primary': '#ffffff',
        'primary-container': '#dff8ed',
        'on-primary-container': '#087853',
        'inverse-primary': '#48d7a7',
        secondary: '#c69214',
        'on-secondary': '#ffffff',
        'secondary-container': '#fff5d6',
        'on-secondary-container': '#8a5c00',
        tertiary: '#0284c7',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#e0f2fe',
        'on-tertiary-container': '#075985',
        error: '#e11d48',
        'on-error': '#ffffff',
        'error-container': '#ffe4e6',
        'on-error-container': '#9f1239',
        'primary-fixed': '#dff8ed',
        'primary-fixed-dim': '#a7f3d0',
        'on-primary-fixed': '#064e3b',
        'on-primary-fixed-variant': '#047857',
        'secondary-fixed': '#fef3c7',
        'secondary-fixed-dim': '#fde68a',
        'on-secondary-fixed': '#78350f',
        'on-secondary-fixed-variant': '#92400e',
        'tertiary-fixed': '#e0f2fe',
        'tertiary-fixed-dim': '#bae6fd',
        'on-tertiary-fixed': '#0c4a6e',
        'on-tertiary-fixed-variant': '#075985',
        background: '#f3f5f9',
        'on-background': '#0f1b2d',
        'surface-variant': '#eef1f5',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        display: ['Montserrat', 'Inter', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'headline-xl': ['40px', {
          lineHeight: '48px',
          fontWeight: '700',
          letterSpacing: '0',
        }],
        'headline-xl-mobile': ['32px', {
          lineHeight: '40px',
          fontWeight: '700',
          letterSpacing: '0',
        }],
        'headline-lg': ['32px', {
          lineHeight: '40px',
          fontWeight: '600',
          letterSpacing: '0',
        }],
        'headline-md': ['24px', {
          lineHeight: '32px',
          fontWeight: '600',
        }],
        'body-lg': ['18px', {
          lineHeight: '28px',
          fontWeight: '400',
        }],
        'body-md': ['16px', {
          lineHeight: '24px',
          fontWeight: '400',
        }],
        'body-sm': ['14px', {
          lineHeight: '20px',
          fontWeight: '400',
        }],
        'label-md': ['12px', {
          lineHeight: '16px',
          fontWeight: '600',
          letterSpacing: '0.05em',
        }],
        'label-sm': ['10px', {
          lineHeight: '12px',
          fontWeight: '700',
          letterSpacing: '0.08em',
        }],
        'data-mono': ['14px', {
          lineHeight: '20px',
          fontWeight: '500',
        }],
      },
      borderRadius: {
        sm: '0.125rem',
        md: '0.375rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'stack-sm': '4px',
        'stack-md': '12px',
        'stack-lg': '24px',
        'section-gap': '64px',
      },
      maxWidth: {
        'container': '1280px',
      },
    },
  },
  plugins: [],
}
