/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        surface: '#f8f9fa',
        'surface-dim': '#d9dadb',
        'surface-bright': '#f8f9fa',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f3f4f5',
        'surface-container': '#edeeef',
        'surface-container-high': '#e7e8e9',
        'surface-container-highest': '#e1e3e4',
        'on-surface': '#191c1d',
        'on-surface-variant': '#44474d',
        'inverse-surface': '#2e3132',
        'inverse-on-surface': '#f0f1f2',
        outline: '#75777e',
        'outline-variant': '#c5c6cd',
        'surface-tint': '#515f78',
        primary: '#000000',
        'on-primary': '#ffffff',
        'primary-container': '#0d1c32',
        'on-primary-container': '#76849f',
        'inverse-primary': '#b9c7e4',
        secondary: '#006c4a',
        'on-secondary': '#ffffff',
        'secondary-container': '#82f5c1',
        'on-secondary-container': '#00714e',
        tertiary: '#735c00',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#cba72f',
        'on-tertiary-container': '#4e3d00',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#d6e3ff',
        'primary-fixed-dim': '#b9c7e4',
        'on-primary-fixed': '#0d1c32',
        'on-primary-fixed-variant': '#39475f',
        'secondary-fixed': '#85f8c4',
        'secondary-fixed-dim': '#68dba9',
        'on-secondary-fixed': '#002114',
        'on-secondary-fixed-variant': '#005137',
        'tertiary-fixed': '#ffe088',
        'tertiary-fixed-dim': '#e9c349',
        'on-tertiary-fixed': '#241a00',
        'on-tertiary-fixed-variant': '#574500',
        background: '#f8f9fa',
        'on-background': '#191c1d',
        'surface-variant': '#e1e3e4',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'headline-xl': ['40px', {
          lineHeight: '48px',
          fontWeight: '700',
          letterSpacing: '-0.02em',
        }],
        'headline-xl-mobile': ['32px', {
          lineHeight: '40px',
          fontWeight: '700',
          letterSpacing: '-0.02em',
        }],
        'headline-lg': ['32px', {
          lineHeight: '40px',
          fontWeight: '600',
          letterSpacing: '-0.01em',
        }],
        'headline-md': ['24px', {
          lineHeight: '32px',
          fontWeight: '600',
        }],
        'body-lg': ['18px', {
          lineHeight: '28px',
          fontWeight: '400',
        }],
        'body-md': ['16px', {
          lineHeight: '24px',
          fontWeight: '400',
        }],
        'body-sm': ['14px', {
          lineHeight: '20px',
          fontWeight: '400',
        }],
        'label-md': ['12px', {
          lineHeight: '16px',
          fontWeight: '600',
          letterSpacing: '0.05em',
        }],
        'label-sm': ['10px', {
          lineHeight: '12px',
          fontWeight: '700',
          letterSpacing: '0.08em',
        }],
        'data-mono': ['14px', {
          lineHeight: '20px',
          fontWeight: '500',
        }],
      },
      borderRadius: {
        sm: '0.125rem',
        md: '0.375rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'stack-sm': '4px',
        'stack-md': '12px',
        'stack-lg': '24px',
        'section-gap': '64px',
      },
      maxWidth: {
        'container': '1280px',
      },
    },
  },
  plugins: [],
}
