import type { BetItem } from '../../services/betService';
import type { NotificationItem } from '../../services/notificationService';
import type { RaceScheduleItem } from '../../services/scheduleService';
import type { RaceResultListItem } from '../../types/raceResult';

const now = Date.now();
const toIso = (offsetMinutes: number) => new Date(now + offsetMinutes * 60 * 1000).toISOString();

export const spectatorDashboardMockData = {
  upcomingRaces: [
    {
      raceId: 101,
      tournamentId: 1,
      tournamentName: 'Summer Cup 2026',
      location: 'Track A',
      raceName: 'Opening Sprint',
      raceNumber: 1,
      rankGroup: 'Elite',
      lapCount: 4,
      scheduledAt: toIso(30),
      predictionClosesAt: toIso(10),
      distanceM: 1200,
      trackType: 'Turf',
      maxHorses: 10,
      registeredHorseCount: 9,
      status: 'live',
      prizePool: 250000000,
    },
    {
      raceId: 102,
      tournamentId: 1,
      tournamentName: 'Summer Cup 2026',
      location: 'Track A',
      raceName: 'Golden Mile',
      raceNumber: 2,
      rankGroup: 'Open',
      lapCount: 6,
      scheduledAt: toIso(90),
      predictionClosesAt: toIso(50),
      distanceM: 1600,
      trackType: 'Turf',
      maxHorses: 12,
      registeredHorseCount: 11,
      status: 'scheduled',
      prizePool: 320000000,
    },
    {
      raceId: 103,
      tournamentId: 2,
      tournamentName: 'City Derby',
      location: 'Track B',
      raceName: 'Night Challenge',
      raceNumber: 3,
      rankGroup: 'Premium',
      lapCount: 5,
      scheduledAt: toIso(180),
      predictionClosesAt: toIso(140),
      distanceM: 1400,
      trackType: 'Synthetic',
      maxHorses: 8,
      registeredHorseCount: 8,
      status: 'upcoming',
      prizePool: 180000000,
    },
    {
      raceId: 104,
      tournamentId: 2,
      tournamentName: 'City Derby',
      location: 'Track B',
      raceName: 'Final Dash',
      raceNumber: 4,
      rankGroup: 'Champion',
      lapCount: 7,
      scheduledAt: toIso(300),
      predictionClosesAt: toIso(260),
      distanceM: 2000,
      trackType: 'Dirt',
      maxHorses: 10,
      registeredHorseCount: 10,
      status: 'upcoming',
      prizePool: 420000000,
    },
    {
      raceId: 105,
      tournamentId: 3,
      tournamentName: 'National Stakes',
      location: 'Track C',
      raceName: 'Rising Star Cup',
      raceNumber: 1,
      rankGroup: 'Novice',
      lapCount: 4,
      scheduledAt: toIso(420),
      predictionClosesAt: toIso(380),
      distanceM: 1000,
      trackType: 'Turf',
      maxHorses: 9,
      registeredHorseCount: 9,
      status: 'upcoming',
      prizePool: 150000000,
    },
    {
      raceId: 106,
      tournamentId: 3,
      tournamentName: 'National Stakes',
      location: 'Track C',
      raceName: 'Storm Runner',
      raceNumber: 2,
      rankGroup: 'Open',
      lapCount: 6,
      scheduledAt: toIso(520),
      predictionClosesAt: toIso(480),
      distanceM: 1800,
      trackType: 'Turf',
      maxHorses: 11,
      registeredHorseCount: 10,
      status: 'upcoming',
      prizePool: 270000000,
    },
  ] as RaceScheduleItem[],

  myPredictions: [
    {
      betId: 201,
      raceId: 101,
      amount: 120000,
      odds: 2.35,
      potentialPayout: 282000,
      status: 'pending',
      createdAt: toIso(-20),
      raceName: 'Opening Sprint',
      tournamentName: 'Summer Cup 2026',
      horseName: 'Silver Arrow',
      jockeyName: 'M. Nguyen',
    },
    {
      betId: 202,
      raceId: 102,
      amount: 80000,
      odds: 3.1,
      potentialPayout: 248000,
      status: 'pending',
      createdAt: toIso(-50),
      raceName: 'Golden Mile',
      tournamentName: 'Summer Cup 2026',
      horseName: 'Midnight Storm',
      jockeyName: 'T. Tran',
    },
    {
      betId: 203,
      raceId: 103,
      amount: 95000,
      odds: 1.9,
      potentialPayout: 180500,
      status: 'won',
      createdAt: toIso(-180),
      raceName: 'Night Challenge',
      tournamentName: 'City Derby',
      horseName: 'Blue Horizon',
      jockeyName: 'H. Le',
    },
    {
      betId: 204,
      raceId: 104,
      amount: 70000,
      odds: 2.8,
      potentialPayout: 196000,
      status: 'lost',
      createdAt: toIso(-260),
      raceName: 'Final Dash',
      tournamentName: 'City Derby',
      horseName: 'Golden Crest',
      jockeyName: 'A. Pham',
    },
    {
      betId: 205,
      raceId: 105,
      amount: 60000,
      odds: 2.1,
      potentialPayout: 126000,
      status: 'pending',
      createdAt: toIso(-340),
      raceName: 'Rising Star Cup',
      tournamentName: 'National Stakes',
      horseName: 'Sunset Blaze',
      jockeyName: 'K. Vo',
    },
  ] as BetItem[],

  latestResults: [
    {
      id: 'result-1',
      raceId: 'r1',
      raceName: 'Riverfront Classic',
      raceNumber: 5,
      tournamentName: 'Spring Championship',
      track: 'Track A',
      date: toIso(-1800),
      status: 'published',
      publishedAt: toIso(-1760),
      totalPrizePool: '₫320,000,000',
      topFinishers: [
        { rank: 1, horseName: 'Lightning Bolt', jockeyName: 'N. Dao', finishTime: '1:22.45' },
        { rank: 2, horseName: 'Wild Banner', jockeyName: 'L. Huynh', finishTime: '1:22.81' },
        { rank: 3, horseName: 'Golden Echo', jockeyName: 'Q. Tran', finishTime: '1:23.04' },
      ],
    },
    {
      id: 'result-2',
      raceId: 'r2',
      raceName: 'Moonlight Stakes',
      raceNumber: 2,
      tournamentName: 'City Derby',
      track: 'Track B',
      date: toIso(-2400),
      status: 'confirmed',
      publishedAt: toIso(-2360),
      totalPrizePool: '₫280,000,000',
      topFinishers: [
        { rank: 1, horseName: 'Neon Legend', jockeyName: 'P. Nguyen', finishTime: '1:18.90' },
        { rank: 2, horseName: 'Red Comet', jockeyName: 'Y. Do', finishTime: '1:19.18' },
        { rank: 3, horseName: 'Steel Wave', jockeyName: 'M. Ly', finishTime: '1:19.44' },
      ],
    },
    {
      id: 'result-3',
      raceId: 'r3',
      raceName: 'Highland Cup',
      raceNumber: 4,
      tournamentName: 'National Stakes',
      track: 'Track C',
      date: toIso(-3600),
      status: 'published',
      publishedAt: toIso(-3560),
      totalPrizePool: '₫195,000,000',
      topFinishers: [
        { rank: 1, horseName: 'Winter Sky', jockeyName: 'S. Bui', finishTime: '1:11.76' },
        { rank: 2, horseName: 'Bright Horizon', jockeyName: 'C. Hoang', finishTime: '1:12.02' },
        { rank: 3, horseName: 'Desert Rose', jockeyName: 'V. Dang', finishTime: '1:12.31' },
      ],
    },
    {
      id: 'result-4',
      raceId: 'r4',
      raceName: 'Valley Sprint',
      raceNumber: 1,
      tournamentName: 'Summer Cup 2026',
      track: 'Track A',
      date: toIso(-4200),
      status: 'published',
      publishedAt: toIso(-4160),
      totalPrizePool: '₫240,000,000',
      topFinishers: [
        { rank: 1, horseName: 'Pacific Star', jockeyName: 'K. Tran', finishTime: '1:09.93' },
        { rank: 2, horseName: 'Silver Line', jockeyName: 'T. Phan', finishTime: '1:10.16' },
        { rank: 3, horseName: 'Fast Current', jockeyName: 'J. Vo', finishTime: '1:10.38' },
      ],
    },
    {
      id: 'result-5',
      raceId: 'r5',
      raceName: 'Sunset Derby',
      raceNumber: 3,
      tournamentName: 'Summer Cup 2026',
      track: 'Track A',
      date: toIso(-5400),
      status: 'confirmed',
      publishedAt: toIso(-5360),
      totalPrizePool: '₫310,000,000',
      topFinishers: [
        { rank: 1, horseName: 'Royal Crown', jockeyName: 'B. Pham', finishTime: '1:26.22' },
        { rank: 2, horseName: 'East Wind', jockeyName: 'D. Le', finishTime: '1:26.60' },
        { rank: 3, horseName: 'Amber Flight', jockeyName: 'R. Nguyen', finishTime: '1:26.94' },
      ],
    },
  ] as RaceResultListItem[],

  notifications: [
    {
      notificationId: 301,
      title: 'Race update',
      message: 'The final gate list for Opening Sprint has been published.',
      createdAt: toIso(-15),
    },
    {
      notificationId: 302,
      title: 'Prediction reminder',
      message: 'Golden Mile predictions close in 40 minutes.',
      createdAt: toIso(-40),
    },
    {
      notificationId: 303,
      title: 'Winner announcement',
      message: 'Night Challenge results have been confirmed.',
      createdAt: toIso(-90),
    },
    {
      notificationId: 304,
      title: 'New race added',
      message: 'A new warm-up race has been scheduled for Track C.',
      createdAt: toIso(-180),
    },
    {
      notificationId: 305,
      title: 'Prize pool update',
      message: 'The prize pool for City Derby has increased by 5%.',
      createdAt: toIso(-300),
    },
  ] as NotificationItem[],
};
